services:
  app:
    profiles: [ "prod" ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contact_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    profiles: [ "prod" ]
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contact_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d contact_management" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    profiles: [ "test" ]
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test_db:5432/contact_management_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=test

  test_db:
    profiles: [ "test" ]
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: contact_management_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d contact_management_test" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  test_db_data: